<a href="https://colab.research.google.com/github/VaishnaviKrishnamoorthy/Guvi_task2/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [11]:
np.__version__

'1.21.6'

In [12]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [16]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [19]:
print(a.size)
print(a.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [21]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [22]:
b=np.zeros(10)
b[4]=1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [23]:
c=np.arange(10,50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [29]:
d=np.arange(1,11)
print(d)
d=d[::-1]
print(d)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [30]:
e=np.arange(9).reshape(3,3)
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [36]:
f=[1,2,0,0,4,0]
np.nonzero(f)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [45]:
np.random.random((3,3,3))

array([[[0.90059715, 0.22601007, 0.39041547],
        [0.64970884, 0.34140559, 0.77670206],
        [0.28186605, 0.47145316, 0.72073008]],

       [[0.14293502, 0.69901837, 0.86830905],
        [0.08500337, 0.12753485, 0.38166688],
        [0.92644826, 0.90554173, 0.71767901]],

       [[0.95110076, 0.54208259, 0.68464535],
        [0.83951297, 0.83013545, 0.14641816],
        [0.26350035, 0.56051715, 0.2465661 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [51]:
g=np.random.random((10,10))
print(g.min())
print(g.max())

0.008446340287928122
0.9813891794093027


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [57]:
h=np.random.random(30)
print(h)
print(h.mean())

[0.76259636 0.80312492 0.31399879 0.91242236 0.26575408 0.34511511
 0.48561839 0.78230569 0.18152634 0.50766251 0.26952472 0.28711986
 0.1095496  0.71758274 0.87665026 0.18535456 0.42133717 0.01077295
 0.02022762 0.04047593 0.30226708 0.02580222 0.95664794 0.71394199
 0.9077369  0.84666741 0.65458139 0.78086731 0.94666367 0.64888073]
0.5027592190407049


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [68]:
i=np.ones((4,4))
print(i)
i[1:-1, 1:-1]=0
print(i)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [81]:
j=np.ones((3,3))
print(j)
j=np.pad(j, pad_width=1, mode='constant',constant_values=0)
print(j)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [85]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [98]:
l=np.diag(np.arange(4)+1,k=-1)
print(l)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [107]:
k=np.zeros((8,8))
print(k)
k[1::2,::2]=1
k[::2,1::2]=1
print(k)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [109]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [110]:
m=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [121]:
n=np.random.random((5,5))
n=(n-n.min())/(n.max()-n.min())
print(n)

[[0.76554496 0.41885919 0.42082179 0.93157542 0.99463025]
 [0.91434767 0.89417578 0.20840981 0.81288479 0.14271812]
 [0.11079305 0.97317179 0.43138678 0.85251609 1.        ]
 [0.71422557 0.73721052 0.75405137 0.5533779  0.        ]
 [0.55467814 0.99601179 0.75710771 0.66132898 0.57536806]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [238]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [125]:
o=np.dot(np.ones((5,3)),np.ones((3,2)))
print(o)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [249]:
p=np.arange(11)
print(p)
p[(3<p)&(p<8)] *= -1
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [130]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [139]:
Z=np.arange(6)
print(Z**Z)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)

[   1    1    4   27  256 3125]
[False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[0. 1. 2. 3. 4. 5.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [142]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [153]:
q=np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(q)),q)

array([-10.,  -2.,  -3.,  -3.,  10.,   4.,   9.,   4.,  -8.,  -7.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [155]:
d=np.array([0, 1, 2, 3, 4])
v=[1, 3, 4]
print(np.intersect1d(d,v))

[1 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [156]:
Z=np.random.random(1000).reshape(10,10,10) * np.nan
np.seterr(all="ignore")
np.nanmedian(Z, axis=[1, 2])

/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py:1120: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [158]:
np.sqrt(-1)==np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [160]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-05-09
Today:  2022-05-10
Tomorrow:  2022-05-11


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [164]:
x=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [165]:
d = np.ones(3)*1
v = np.ones(3)*2
j = np.ones(3)*3
np.add(d,v,out=v)
np.divide(d,2,out=d)
np.negative(d,out=d)
np.multiply(d,v,out=v)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [180]:
a = np.random.uniform(0,10,10)
print (a - a%1)
print (np.floor(a))
print (np.ceil(a)-1)
print (a.astype(int))
print (np.trunc(a))

[8. 0. 5. 4. 7. 0. 2. 8. 9. 3.]
[8. 0. 5. 4. 7. 0. 2. 8. 9. 3.]
[8. 0. 5. 4. 7. 0. 2. 8. 9. 3.]
[8 0 5 4 7 0 2 8 9 3]
[8. 0. 5. 4. 7. 0. 2. 8. 9. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [184]:
x=np.zeros((5,5))
x+=np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [186]:
def generator():
  for i in range(10):
        yield i
a=np.fromiter(generator(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [188]:
b=np.linspace(start=0,stop=11,num=10,endpoint=False)
print(b)

[0.  1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [190]:
c=np.random.random(size=10)
c.sort()
print(c)

[0.03283736 0.06038884 0.09610964 0.10489709 0.47622035 0.624113
 0.63223792 0.78304558 0.85512938 0.963878  ]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [191]:
d=np.arange(10)
np.add.reduce(d)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [195]:
A=np.random.random((2,5))
B=np.random.random((2,5))
c=np.allclose(A,B)
d=np.array_equal(A,B)
print(c)
print(d)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [196]:
s=np.zeros(10) 
s.flags.writeable = False 
print(s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [199]:
a=np.random.random((10,2))
x,y=a[:,0], a[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.72540081 0.71218376 0.82816263 0.79012666 0.44705644 0.28577905
 1.07289035 0.86573199 0.63979094 1.05438024]
[0.64626262 1.41082389 0.24234752 0.98382802 0.64425531 1.03531217
 0.94616009 0.20253022 0.48309812 1.16952842]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [201]:
m=np.random.random(10)
m[m.argmax()] = 0
print(m)

[0.2835648  0.95568826 0.38191168 0.0094399  0.         0.88469788
 0.27245729 0.17639112 0.33966804 0.7642829 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [203]:
Z=np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [209]:
X=np.random.random((5,5))
Y=np.random.random((5,5))
c=1/(x-y)
C=1/np.subtract.outer(X, Y)
np.linalg.det(c)

-170918.52071624406

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [210]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [211]:
np.set_printoptions(threshold=float("inf"))
a=np.ones((10,10))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [214]:
c=np.arange(100)
d=np.random.uniform(0,100)
index=(np.abs(c-d)).argmin()
print(c[index])

56


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [215]:
a=np.zeros(10,[('position',[('x',float,1),
                            ('y',float,1)]),
               ('color',[('r',float,1),
                         ('g',float,1),
                         ('b',float,1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [216]:
z=np.random.random((10,2))
x,y=np.atleast_2d(z[:,0],z[:,1])
d=np.sqrt((x-x.T)**2 +(y-y.T)**2)
print(d)

[[0.         0.09697516 0.88880891 0.52357985 0.86264584 0.90017771
  0.88540813 0.41870948 0.16838937 0.25938475]
 [0.09697516 0.         0.7961638  0.42669561 0.7678269  0.82637931
  0.81115804 0.32242394 0.10185626 0.176838  ]
 [0.88880891 0.7961638  0.         0.42587589 0.07825622 0.82112325
  0.80835862 0.52567105 0.78928344 0.6341662 ]
 [0.52357985 0.42669561 0.42587589 0.         0.37480457 0.56870321
  0.55267236 0.10926811 0.38858326 0.31777534]
 [0.86264584 0.7678269  0.07825622 0.37480457 0.         0.7431563
  0.73048564 0.47974676 0.75169502 0.61429475]
 [0.90017771 0.82637931 0.82112325 0.56870321 0.7431563  0.
  0.01622237 0.590936   0.73270131 0.81978935]
 [0.88540813 0.81115804 0.80835862 0.55267236 0.73048564 0.01622237
  0.         0.57472282 0.71779464 0.80371671]
 [0.41870948 0.32242394 0.52567105 0.10926811 0.47974676 0.590936
  0.57472282 0.         0.27938407 0.23948543]
 [0.16838937 0.10185626 0.78928344 0.38858326 0.75169502 0.73270131
  0.71779464 0.27938407

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [217]:
a=np.arange(10, dtype=np.float32)
a=a.astype(np.int32,copy=False)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [218]:
from io import StringIO
fe=StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z=np.genfromtxt(fe, delimiter=",", dtype=np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [219]:
s=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(s):
    print(index, value)
for index in np.ndindex(s.shape):
    print(index, s[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [220]:
x,y=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma,mu=1.0, 0.0
g=np.exp(-((d-mu)**2/(2.0*sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [228]:
n=4
p=3
z=np.zeros((n,n))
np.put(z,np.random.choice(range(n*n), p, replace=False),1)
print(z)

[[0. 0. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [230]:
x=np.random.rand(5,5)
y=x-x.mean(axis=1, keepdims=True)
y=x-x.mean(axis=1).reshape(-1, 1)
print(y)

[[ 0.33189719 -0.45239008  0.06555901  0.39354981 -0.33861593]
 [ 0.1801713  -0.09267711  0.14244386 -0.55041689  0.32047883]
 [-0.20531072  0.06987761  0.14756472  0.24477919 -0.2569108 ]
 [ 0.00331753 -0.09405641  0.08193537 -0.10219356  0.11099708]
 [ 0.30846593  0.24933158 -0.17920089 -0.32676787 -0.05182875]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [231]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[8 0 3]
 [0 5 6]
 [8 0 2]]
[[8 0 3]
 [8 0 2]
 [0 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [232]:
Z=np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [237]:
Z=np.random.uniform(0,1,10)
z=0.5
m=Z.flat[np.abs(Z-z).argmin()]
print(m)

0.5673579353259595


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [239]:
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None])
for x,y,z in it:z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [240]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
z= NamedArray(np.arange(10), "range_10")
print(z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [244]:
z=np.ones(10)
p=np.random.randint(0,len(z),20)
z+=np.bincount(p,minlength=len(z))
print(z)
np.add.at(z,p,1)
print(z)

[3. 3. 4. 5. 2. 4. 2. 3. 2. 2.]
[5. 5. 7. 9. 3. 7. 3. 5. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [245]:
a=[1,2,3,4,5,6]
b=[1,3,9,3,4,1]
c=np.bincount(b,a)
print(c)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [246]:
w,h=16,16
i=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f=i[...,0]*(256*256)+i[...,1]*256+i[...,2]
n=len(np.unique(f))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [247]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[73 70 57 62]
 [58 41 60 58]
 [56 55 49 65]]
[[73 70 57 62]
 [58 41 60 58]
 [56 55 49 65]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [248]:
D=np.random.uniform(0,1,100)
S=np.random.randint(0,10,100)
D_sums=np.bincount(S, weights=D)
D_counts=np.bincount(S)
D_means=D_sums/D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.48206917 0.37306477 0.48094324 0.50211761 0.58524533 0.58513234
 0.47068672 0.46835411 0.64717704 0.41803866]
0    0.482069
1    0.373065
2    0.480943
3    0.502118
4    0.585245
5    0.585132
6    0.470687
7    0.468354
8    0.647177
9    0.418039
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [252]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
np.diag(np.dot(a,b))

array([1.99175055, 0.63368607, 1.33828844, 1.50756171, 1.10690637])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [254]:
Z=np.array([1,2,3,4,5])
nz=3
Z0=np.zeros(len(Z)+(len(Z)-1)*(nz))
Z0[::nz+1]=Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [255]:
A=np.ones((5,5,3))
B=2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [256]:
A=np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [257]:
faces=np.random.randint(0,100,(10,3))
f=np.roll(faces.repeat(2,axis=1),-1,axis=1)
f=f.reshape(len(f)*3,2)
F=np.sort(f,axis=1)
g=f.view(dtype=[('p0',f.dtype),('p1',f.dtype)] )
g=np.unique(g)
print(g)

[( 0, 75) ( 0, 98) ( 2,  2) ( 2, 71) ( 9,  0) (12, 92) (15, 82) (15, 83)
 (16, 40) (16, 57) (30, 55) (31, 16) (35, 30) (37, 15) (40, 31) (55, 35)
 (57, 90) (57, 92) (60, 57) (62, 12) (71,  2) (72, 15) (75,  9) (82,  0)
 (82, 72) (83, 37) (90, 60) (92, 16) (92, 62) (98, 82)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [258]:
C=np.bincount([1,1,2,3,4,4,6])
A=np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [259]:
def moving_average(a,n=3) :
    ret=np.cumsum(a, dtype=float)
    ret[n:]=ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z=np.arange(20)
print(moving_average(Z,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [260]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape=(a.size - window + 1, window)
    strides=(a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z=rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [261]:
z=np.random.randint(0,2,100)
np.logical_not(z,out=z)

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1])

In [262]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.81950113,  0.34933612, -0.56073272, -0.98329698,  0.77360856,
        0.82305514, -0.657998  , -0.40485704,  0.61964265,  0.26890815,
       -0.79458294, -0.55435687,  0.55455159,  0.65973899,  0.57003841,
       -0.61186619,  0.42494531, -0.350493  ,  0.92030181,  0.27937403,
        0.2610883 , -0.04771174, -0.70830439, -0.27521301,  0.51708991,
       -0.83966165, -0.28095026, -0.25841378, -0.90019551, -0.82770318,
       -0.33922867, -0.65986719, -0.24411591, -0.41403337, -0.13951701,
        0.30588006,  0.02639821, -0.94202787, -0.15670763,  0.85744313,
       -0.26832165, -0.13276202, -0.1631412 , -0.24982032,  0.63328351,
       -0.12438938, -0.97967636,  0.43788159,  0.17318774,  0.10612492,
        0.58339948,  0.55191676,  0.20243588,  0.5901973 , -0.17830003,
       -0.02976743, -0.24489395, -0.68838568,  0.21183739,  0.88267702,
        0.52249822, -0.47348123, -0.46760802,  0.27638577,  0.97009476,
        0.22637093, -0.49615671, -0.59546737, -0.64703803,  0.19

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [263]:
def distance(P0,P1,p):
    t=P1 - P0
    l=(t**2).sum(axis=1)
    u=-((P0[:,0]-p[...,0])*t[:,0] + (P0[:,1]-p[...,1])*t[:,1]) / l
    u=u.reshape(len(u),1)
    d=P0+u*t-p
    return np.sqrt((d**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.25725747  4.88684083 17.04196056 12.8142435  14.67396687  7.76007797
  1.30542359  0.02925994  5.6525914  11.95962597]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [265]:
P0=np.random.uniform(-10, 10, (10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.06116289 11.773455   11.33531978  7.4550761   3.11079405  0.39897487
  10.9643807   1.80957497  3.58063927  9.96942492]
 [14.49427192  4.23637717 11.98285758  8.07365229 10.68436745 15.17405144
   3.83256587  8.81720548  9.87340264  6.00542959]
 [ 7.65836965  4.54566029 11.59961652  0.43465531  3.10493731  7.06061693
   4.29277197  2.96857561  2.48008053  2.75801961]
 [ 7.66341826 11.92308048  5.67826311  1.64096502 10.65685062  5.02215527
  16.32915585 13.68353595 11.73598767 10.48167247]
 [13.71465203  6.87934596  7.07668403 12.39372027 10.77548605 16.05597267
   4.73476871  7.10087089  9.72767571  8.53564274]
 [ 3.83559664  2.98282947  2.74793855  4.20488447  0.56371994  5.73368538
   5.58792173  2.16602146  0.41548131  1.38885126]
 [ 3.29694574  1.97662575  4.82230716 11.73811603  1.44819604  7.89679055
   3.39219946  4.254006    0.08347874  3.3939353 ]
 [ 3.69772859  2.88392113  5.32338591 12.80657694  1.99545506  8.56706189
   2.71890032  4.02408669  0.59203961  4.28777207]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [266]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 0 6 8 9 0 0 7 7 6]
 [8 5 4 6 3 7 0 5 4 8]
 [7 9 6 7 2 3 7 4 0 7]
 [5 0 0 6 0 6 5 8 6 5]
 [3 8 5 4 2 4 2 8 6 7]
 [4 6 5 9 9 8 9 8 8 2]
 [0 0 4 1 8 9 0 3 0 1]
 [2 2 6 8 8 7 4 3 9 0]
 [7 5 7 6 6 2 0 3 0 9]
 [8 4 8 1 8 3 0 7 7 3]]
[[0 0 0 0 0]
 [0 3 0 6 8]
 [0 8 5 4 6]
 [0 7 9 6 7]
 [0 5 0 0 6]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [267]:
Z=np.arange(1,15,dtype=np.uint32)
R=stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [268]:
Z=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(Z)
rank=np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [269]:
Z=np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [270]:
Z=np.random.randint(0,5,(10,10))
n=3
i=1+(Z.shape[0]-3)
j=1+(Z.shape[1]-3)
C=stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 3 0]
   [1 0 0]
   [1 1 3]]

  [[3 0 2]
   [0 0 2]
   [1 3 0]]

  [[0 2 1]
   [0 2 4]
   [3 0 0]]

  [[2 1 0]
   [2 4 3]
   [0 0 0]]

  [[1 0 0]
   [4 3 2]
   [0 0 1]]

  [[0 0 3]
   [3 2 4]
   [0 1 2]]

  [[0 3 0]
   [2 4 4]
   [1 2 0]]

  [[3 0 2]
   [4 4 0]
   [2 0 4]]]


 [[[1 0 0]
   [1 1 3]
   [3 3 3]]

  [[0 0 2]
   [1 3 0]
   [3 3 2]]

  [[0 2 4]
   [3 0 0]
   [3 2 0]]

  [[2 4 3]
   [0 0 0]
   [2 0 3]]

  [[4 3 2]
   [0 0 1]
   [0 3 4]]

  [[3 2 4]
   [0 1 2]
   [3 4 4]]

  [[2 4 4]
   [1 2 0]
   [4 4 1]]

  [[4 4 0]
   [2 0 4]
   [4 1 3]]]


 [[[1 1 3]
   [3 3 3]
   [0 2 3]]

  [[1 3 0]
   [3 3 2]
   [2 3 3]]

  [[3 0 0]
   [3 2 0]
   [3 3 2]]

  [[0 0 0]
   [2 0 3]
   [3 2 4]]

  [[0 0 1]
   [0 3 4]
   [2 4 3]]

  [[0 1 2]
   [3 4 4]
   [4 3 4]]

  [[1 2 0]
   [4 4 1]
   [3 4 0]]

  [[2 0 4]
   [4 1 3]
   [4 0 0]]]


 [[[3 3 3]
   [0 2 3]
   [3 4 4]]

  [[3 3 2]
   [2 3 3]
   [4 4 0]]

  [[3 2 0]
   [3 3 2]
   [4 0 0]]

  [[2 0 3]
   [3 2 4]
   [0 0 2]]

  [[0 3 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [271]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  8  4 11 16]
 [ 8  1  9  4 16]
 [ 4  9  2 42 10]
 [11  4 42  6 14]
 [16 16 10 14  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [272]:
p,n= 10, 20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [273]:
Z=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [274]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(10): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
  0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1
  0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [275]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9999 9997 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [276]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [282]:
z=np.array([("hello",2.5,3),
            ("world",3.6,2)])
r=np.core.records.fromarrays(z.T,names='col1,col2,col3',formats='S8,f8,i8')
print(r)

[(b'hello', 2.5, 3) (b'world', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [283]:
x=np.random.random(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.73 s per loop
10 loops, best of 5: 133 ms per loop
10 loops, best of 5: 118 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [284]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[..., np.newaxis, np.newaxis] == B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [285]:
Z=np.random.randint(0,5,(10,3))
print(Z)
E=np.all(Z[:,1:] == Z[:,:-1], axis=1)
U=Z[~E]
print(U)
U=Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 1 2]
 [3 3 2]
 [4 4 4]
 [2 3 0]
 [4 2 4]
 [1 1 0]
 [4 0 1]
 [2 4 2]
 [4 0 3]
 [4 2 1]]
[[3 1 2]
 [3 3 2]
 [2 3 0]
 [4 2 4]
 [1 1 0]
 [4 0 1]
 [2 4 2]
 [4 0 3]
 [4 2 1]]
[[3 1 2]
 [3 3 2]
 [2 3 0]
 [4 2 4]
 [1 1 0]
 [4 0 1]
 [2 4 2]
 [4 0 3]
 [4 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [286]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [287]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]
[[0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [288]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.01725648, 0.12947575, 0.59640739, 0.34637725, 0.11542211,
        0.2915343 , 0.61967316, 0.21324018, 0.1393108 , 0.16022517],
       [0.02259171, 0.1695061 , 0.78080021, 0.4534676 , 0.15110746,
        0.38166872, 0.81125913, 0.2791682 , 0.18238188, 0.20976241],
       [0.00535306, 0.0401641 , 0.1850089 , 0.10744815, 0.03580458,
        0.09043557, 0.19222607, 0.06614829, 0.04321499, 0.04970274],
       [0.00869628, 0.06524835, 0.30055512, 0.17455427, 0.05816612,
        0.14691657, 0.31227973, 0.10746082, 0.07020465, 0.0807443 ],
       [0.02285239, 0.17146198, 0.78980963, 0.45870003, 0.15285104,
        0.38607268, 0.82062   , 0.28238943, 0.18448633, 0.21218279],
       [0.01273601, 0.09555857, 0.44017383, 0.25564103, 0.08518639,
        0.21516462, 0.45734495, 0.15738025, 0.10281725, 0.11825294],
       [0.02312805, 0.17353026, 0.79933679, 0.46423315, 0.15469482,
        0.39072972, 0.83051882, 0.28579579, 0.18671171, 0.21474227],
       [0.01343337, 0.10079084, 0.4642753

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [294]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)
#print(y_int)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [295]:
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n=4
M=np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M&=(X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [296]:
X=np.random.randn(100) 
N=1000 
idx=np.random.randint(0, X.size, (N, X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12263189  0.23380199]
